<?php

namespace AppBundle\Repository;

/**
 * CityDistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityDistrictRepository extends \Doctrine\ORM\EntityRepository
{
}
