<?php

namespace AppBundle\Repository;

/**
 * PropertyConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
