<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Property;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return Property|null
     */
    public function findProperty()
    {
        return null;
    }
}
