<?php

namespace AppBundle\Repository;

/**
 * PropertyConstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyConstructionRepository extends \Doctrine\ORM\EntityRepository
{
}
