<?php

namespace AppBundle\Repository;

/**
 * PropertyDispositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyDispositionRepository extends \Doctrine\ORM\EntityRepository
{
}
