imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!crawler', '!notifications']
        crawler:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/crawler_prod.log'
            channels: ['crawler']
        notifications:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/notifications_prod.log'
            channels: ['notifications']
        console:
            type: console
