# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    crawler.sreality.sourceUrl: https://www.sreality.cz/api/cs/v2/estates
    crawler.bezrealitky.sourceUrl: https://www.bezrealitky.cz
    crawler.bazos.sourceUrl: https://reality.bazos.cz
    expo.notifications.backendUrl: https://exp.host/--/api/v2/push/send
    expo.notifications.receiptsBackendUrl: https://exp.host/--/api/v2/push/getReceipts

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: ../../src/AppBundle/{Command}
    # override to inject specific logger instance
    AppBundle\Command\ImportNewAdvertsCommand:
        arguments:
            $logger: '@monolog.logger.crawler'
    AppBundle\Command\PushNotificationsReceiptsCommand:
        arguments:
            $logger: '@monolog.logger.notifications'
            $expoBackendUrl: '%expo.notifications.receiptsBackendUrl%'
    AppBundle\Command\PushNotificationsTestCommand:
        arguments:
            $logger: '@monolog.logger.notifications'
            $expoBackendUrl: '%expo.notifications.backendUrl%'
    AppBundle\Command\PushNotificationsSendCommand:
        arguments:
            $logger: '@monolog.logger.notifications'
            $expoBackendUrl: '%expo.notifications.backendUrl%'

    AppBundle\Service\SrealityCrawler:
        arguments:
            $sourceUrl: '%crawler.sreality.sourceUrl%'
            $logger: '@monolog.logger.crawler'
    AppBundle\Service\BezrealitkyCrawler:
        arguments:
            $sourceUrl: '%crawler.bezrealitky.sourceUrl%'
            $logger: '@monolog.logger.crawler'
    AppBundle\Service\BazosCrawler:
        arguments:
            $sourceUrl: '%crawler.bazos.sourceUrl%'
            $logger: '@monolog.logger.crawler'
