monolog:
    channels: ["crawler", "notifications"]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!crawler', '!notifications']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        crawler:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/crawler_prod.log'
            channels: ['crawler']
        notifications:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/notifications_prod.log'
            channels: ['notifications']
